### ISSUE TITLE
Broken link in bibliography

### ISSUE THREAD

**Issue by BokChoyWarrior** [andredesousa/typescript-best-practices#1]
The final link in the [bibliography](https://github.com/andredesousa/typescript-best-practices#bibliography) named [Typescript Best Practices](https://engineering.zalando.com/posts/2019/02/typescript-best-practices.html) is broken.

-------
Other than that, thanks for the great resource! I will be referring to it lots over the coming months.

**Comment by andredesousa** [comment]
Hi @BokChoyWarrior, thanks for your feedback. Other than that, the link works.

**Comment by BokChoyWarrior** [comment]
Oh sorry for the false alarm, I guess it must have just been down yesterday ^^

Thanks once again!
